services:
  init-permissions:
    image: alpine:latest
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-import:/import
    command: |
      sh -c "
        mkdir -p /data /logs /import &&
        chown -R 7474:7474 /data /logs /import &&
        chmod -R 755 /data /logs /import
      "
    user: "0:0"

  neo4j:
    image: neo4j:2025.03.0-enterprise
    container_name: memento-neo4j
    platform: linux/amd64
    user: "7474:7474"
    depends_on:
      - init-permissions
    environment:
      - NEO4J_AUTH=neo4j/memento_password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_server_bolt_enabled=true
      - NEO4J_server_http_enabled=true
      - NEO4J_server_memory_pagecache_size=768M
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1536M
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-import:/import
