services:
  neo4j:
    image: neo4j:2025.03.0-enterprise
    container_name: memento-neo4j
    platform: linux/amd64
    user: "${UID:-1000}:${GID:-1000}"
    command: bash -c "mkdir -p /logs && chown neo4j:neo4j /logs && exec /docker-entrypoint.sh neo4j"
    environment:
      - NEO4J_AUTH=neo4j/memento_password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_server_memory_pagecache_size=768M
      - NEO4J_server_memory_heap_max__size=1536M
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-import:/import
  memento-mcp:
    image: emasoudy/memento-mcp:latest
    container_name: memento-mcp
    environment:
      - MEMORY_STORAGE_TYPE=neo4j
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=memento_password
      - OPENAI_API_KEY=your-openai-api-key
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small
    depends_on:
      - neo4j
